name: huawei_analytics_example
version: 5.0.3+300
description: Demonstrates how to use the Huawei Analytics plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_analytics:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

